// Class automatically generated by Dev-C++ New Class wizard

#include "sotb_landscapedesc.h"

SOTB_LandscapeCoord LandscapeCoord[] =
{
    SOTB_LandscapeCoord( 640.0f, 300.0f,   0.0f,     40.0f,  1000.0f,  0.0f, 1, NULL,                         false ),
    SOTB_LandscapeCoord( 128.0f, 128.0f,   150.0f,   10.0f,   999.0f,  0.0f, 1, "Graphics\\Lune.png",      true  ),
    SOTB_LandscapeCoord( 512.0f,  64.0f, -1024.0f,  158.0f,   800.0f, 15.0f, 5, "Graphics\\Nuages0.png",   true  ),
    SOTB_LandscapeCoord( 512.0f,  64.0f, -1024.0f,  111.0f,   750.0f, 12.0f, 5, "Graphics\\Nuages1.png",   true  ),
    SOTB_LandscapeCoord( 512.0f,  32.0f, -1024.0f,   64.0f,   700.0f,  9.0f, 5, "Graphics\\Nuages2.png",   true  ),
    SOTB_LandscapeCoord( 512.0f,  16.0f, -1024.0f,   33.0f,   650.0f,  6.0f, 5, "Graphics\\Nuages3.png",   true  ),
    SOTB_LandscapeCoord( 512.0f,   8.0f, -1024.0f,   10.0f,   600.0f,  3.0f, 5, "Graphics\\Nuages4.png",   true  ),
    SOTB_LandscapeCoord( 640.0f, 146.0f,  -640.0f,  -43.0f,   300.0f,  1.0f, 3, "Graphics\\Montagnes.png", true  ),
    SOTB_LandscapeCoord( 512.0f,   4.0f, -1024.0f, -118.0f,   250.0f,  3.0f, 5, "Graphics\\Herbe0.bmp",    true  ),
    SOTB_LandscapeCoord( 512.0f,   8.0f, -1024.0f, -124.0f,   200.0f,  6.0f, 5, "Graphics\\Herbe1.bmp",    true  ),
    SOTB_LandscapeCoord( 512.0f,  16.0f, -1024.0f, -134.0f,   150.0f,  9.0f, 5, "Graphics\\Herbe2.bmp",    true  ),
    SOTB_LandscapeCoord( 512.0f,  16.0f, -1024.0f, -148.0f,   100.0f, 12.0f, 5, "Graphics\\Herbe3.bmp",    true  ),
    SOTB_LandscapeCoord( 512.0f,  32.0f, -1024.0f, -170.0f,    50.0f, 15.0f, 5, "Graphics\\Herbe4.bmp",    true  ),
    SOTB_LandscapeCoord( 512.0f,  32.0f, -1024.0f, -170.0f,     1.0f, 15.0f, 5, "Graphics\\Barriere.png",  true  ),
    SOTB_LandscapeCoord( 552.0f, 512.0f,     0.0f,    0.0f,     0.0f,  0.0f, 1, "Graphics\\Firework.png",  true  ),
    SOTB_LandscapeCoord()
};
