// Class automatically generated by Dev-C++ New Class wizard

#ifndef SOTB_LANDSCAPECOORD_H
#define SOTB_LANDSCAPECOORD_H

#include <windows.h>

/*
 * No description
 */
struct SOTB_LandscapeCoord
{
    float Width;
    float Height;
    float X;
    float Y;
    float Z;
    float Velocity;

    bool  Transparency;
    bool  IsLast;

    int   NbElements;

    LPSTR Filename;

    SOTB_LandscapeCoord();

    SOTB_LandscapeCoord( float Width,
                         float Height,
                         float X,
                         float Y,
                         float Z,
                         float Velocity,
                         int   NbElements,
                         LPSTR Filename,
                         bool  Transparency,
                         bool  IsLast        = false );
};

#endif // SOTB_LANDSCAPECOORD_H
