// Class automatically generated by Dev-C++ New Class wizard

#ifndef SOTB_LANDSCAPEDESC_H
#define SOTB_LANDSCAPEDESC_H

#include "sotb_landscapecoord.h"

extern SOTB_LandscapeCoord LandscapeCoord[];

#endif // SOTB_LANDSCAPEDESC_H
