// Class automatically generated by Dev-C++ New Class wizard

#ifndef SOTB_LANDSCAPE_H
#define SOTB_LANDSCAPE_H

#include "sotb_element.h"
#include "sotb_landscapedesc.h"

#include "e_sprite.h"

#include <d3dx9.h>
#include <windows.h>

inline DWORD FToDW( FLOAT f )
{
    return *( (DWORD*)&f );
}

class SOTB_LandscapeContainer
{
  private:

    SOTB_Element*            p_Element;
    SOTB_LandscapeContainer* p_Next;

  public:

    SOTB_LandscapeContainer();
    SOTB_LandscapeContainer( SOTB_Element* Element );
    ~SOTB_LandscapeContainer();

  public:

    SOTB_Element* GetElement();

    bool CreateElement( int Index, LPDIRECT3DDEVICE9 theD3DDevice );

    SOTB_LandscapeContainer* GetNextContainer();
    void SetNextContainer( SOTB_LandscapeContainer* Container );
};

/*
 * No description
 */
class SOTB_Landscape
{
  private:

    E_Sprite*                p_Trees;
    E_Sprite*                p_Zeppelin;

    SOTB_LandscapeContainer* p_First;
    SOTB_LandscapeContainer* p_Current;

    BOOL                     p_Fog;

    float                    p_FogStart;
    float                    p_FogEnd;

    int                      p_TreesXOffset;

  public:

    SOTB_Landscape();
    ~SOTB_Landscape();

  public:

    bool Initialize( LPDIRECT3DDEVICE9 theD3DDevice );
    bool Restore( LPDIRECT3DDEVICE9 theD3DDevice );

    void Render( LPDIRECT3DDEVICE9 theD3DDevice );
    void Scroll();
};

#endif // SOTB_LANDSCAPE_H
