// Class automatically generated by Dev-C++ New Class wizard

#include "sotb_landscapecoord.h"

SOTB_LandscapeCoord::SOTB_LandscapeCoord()
{
    Width        = 1.0f;
    Height       = 1.0f;
    X            = 0.0f;
    Y            = 0.0f;
    Z            = 0.0f;
    Velocity     = 0.0f;
    NbElements   = 0;
    Filename     = "";
    Transparency = false;
    IsLast       = true;
}

SOTB_LandscapeCoord::SOTB_LandscapeCoord( float Width,
                                          float Height,
                                          float X,
                                          float Y,
                                          float Z,
                                          float Velocity,
                                          int   NbElements,
                                          LPSTR Filename,
                                          bool  Transparency,
                                          bool  IsLast )
{
    this->Width        = Width;
    this->Height       = Height;
    this->X            = X;
    this->Y            = Y;
    this->Z            = Z;
    this->Velocity     = Velocity;
    this->NbElements   = NbElements;
    this->Filename     = Filename;
    this->Transparency = Transparency;
    this->IsLast       = IsLast;
}
