# Project: NormalsTable
# Compiler: Default GCC compiler
# Compiler Type: MingW 3
# Makefile created by wxDev-C++ IDE 7.4.2.569 on 08.11.18 13:08

WXLIBNAME = wxmsw29u
CPP       = g++.exe
CC        = gcc.exe
WINDRES   = "windres.exe"
OBJ       = DEFAUL~1/e_md2normalsdatas.o DEFAUL~1/e_md2generatetable.o DEFAUL~1/main.o DEFAUL~1/NormalsTable_private.res
LINKOBJ   = "DEFAUL~1/e_md2normalsdatas.o" "DEFAUL~1/e_md2generatetable.o" "DEFAUL~1/main.o" DEFAUL~1/NormalsTable_private.res
LIBS      = -L"C:/Program Files (x86)/Dev-Cpp/lib/wx/gcc_lib" -L"C:/Program Files (x86)/Dev-Cpp/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" "C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Lib/x86/d3d9.lib"  -g3 
INCS      = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Include/"
CXXINCS   = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/" -I"C:/Program Files (x86)/Dev-Cpp/include/common" -I"C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)/Include/"
RCINCS    = --include-dir "C:/PROGRA~2/Dev-Cpp/include/common"
BIN       = DEFAUL~1/NormalsTable.exe
DEFINES   = 
CXXFLAGS  = $(CXXINCS) $(DEFINES)   -g3
CFLAGS    = $(INCS) $(DEFINES)   -g3
GPROF     = gprof.exe
ifeq ($(OS),Windows_NT)
   RM = del /Q
   FixPath = $(subst /,\,$1)
else
   RM = rm -f
   FixPath = $1
endif
LINK      = g++.exe

.PHONY: all all-before all-after clean clean-custom
all: all-before $(BIN) all-after

clean: clean-custom
	$(RM) $(call FixPath,$(LINKOBJ)) "$(call FixPath,$(BIN))"

$(BIN): $(OBJ)
	$(LINK) $(LINKOBJ) -o "$(BIN)" $(LIBS) 

DEFAUL~1/e_md2normalsdatas.o: $(GLOBALDEPS) e_md2normalsdatas.cpp e_md2normalsdatas.h
	$(CPP) -c e_md2normalsdatas.cpp -o DEFAUL~1/e_md2normalsdatas.o $(CXXFLAGS)

DEFAUL~1/e_md2generatetable.o: $(GLOBALDEPS) e_md2generatetable.cpp e_md2generatetable.h e_md2normalsdatas.h
	$(CPP) -c e_md2generatetable.cpp -o DEFAUL~1/e_md2generatetable.o $(CXXFLAGS)

DEFAUL~1/main.o: $(GLOBALDEPS) main.cpp e_md2generatetable.h e_md2normalsdatas.h
	$(CPP) -c main.cpp -o DEFAUL~1/main.o $(CXXFLAGS)

DEFAUL~1/NormalsTable_private.res: DEFAUL~1/NormalsTable_private.rc 
	$(WINDRES) --input-format=rc -o DEFAUL~1/NormalsTable_private.res $(RCINCS) DEFAUL~1/NORMAL~1.RC -O coff
