# Project: Animation
# Compiler: Default GCC compiler
# Compiler Type: MingW 3
# Makefile created by wxDev-C++ IDE 7.4.2.569 on 08.11.18 16:44

WXLIBNAME = wxmsw29u
CPP       = g++.exe
CC        = gcc.exe
WINDRES   = "windres.exe"
OBJ       = Win32/Debug/e_camera.o Win32/Debug/e_md2mesh.o Win32/Debug/animationlist.o Win32/Debug/application.o Win32/Debug/main.o Win32/Debug/Animation_private.res
LINKOBJ   = "Win32/Debug/e_camera.o" "Win32/Debug/e_md2mesh.o" "Win32/Debug/animationlist.o" "Win32/Debug/application.o" "Win32/Debug/main.o" Win32/Debug/Animation_private.res
LIBS      = -L"C:/Program Files (x86)/Dev-Cpp/lib/wx/gcc_lib" -L"C:/Program Files (x86)/Dev-Cpp/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" "C:/Program Files (x86)/Dev-Cpp/lib/libd3d9.a" "C:/Program Files (x86)/Dev-Cpp/lib/libd3dx9.a" "C:/Program Files (x86)/Dev-Cpp/lib/libdinput8.a" "C:/Program Files (x86)/Dev-Cpp/lib/libdxguid.a" "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.17134.0/um/x86/WinMM.Lib"  -g3 
INCS      = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/include/"
CXXINCS   = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/" -I"C:/Program Files (x86)/Dev-Cpp/include/common" -I"C:/Program Files (x86)/Dev-Cpp/include/"
RCINCS    = --include-dir "C:/PROGRA~2/Dev-Cpp/include/common"
BIN       = Win32/Debug/Animation.exe
DEFINES   = 
CXXFLAGS  = $(CXXINCS) $(DEFINES)   -g3
CFLAGS    = $(INCS) $(DEFINES)   -g3
GPROF     = gprof.exe
ifeq ($(OS),Windows_NT)
   RM = del /Q
   FixPath = $(subst /,\,$1)
else
   RM = rm -f
   FixPath = $1
endif
LINK      = g++.exe

.PHONY: all all-before all-after clean clean-custom
all: all-before $(BIN) all-after

clean: clean-custom
	$(RM) $(call FixPath,$(LINKOBJ)) "$(call FixPath,$(BIN))"

$(BIN): $(OBJ)
	$(LINK) $(LINKOBJ) -o "$(BIN)" $(LIBS) 

Win32/Debug/e_camera.o: $(GLOBALDEPS) e_camera.cpp e_camera.h
	$(CPP) -c e_camera.cpp -o Win32/Debug/e_camera.o $(CXXFLAGS)

Win32/Debug/e_md2mesh.o: $(GLOBALDEPS) e_md2mesh.cpp e_md2mesh.h
	$(CPP) -c e_md2mesh.cpp -o Win32/Debug/e_md2mesh.o $(CXXFLAGS)

Win32/Debug/animationlist.o: $(GLOBALDEPS) animationlist.cpp animationlist.h e_md2mesh.h
	$(CPP) -c animationlist.cpp -o Win32/Debug/animationlist.o $(CXXFLAGS)

Win32/Debug/application.o: $(GLOBALDEPS) application.cpp application.h e_camera.h e_md2mesh.h animationlist.h e_md2mesh.h
	$(CPP) -c application.cpp -o Win32/Debug/application.o $(CXXFLAGS)

Win32/Debug/main.o: $(GLOBALDEPS) main.cpp application.h e_camera.h e_md2mesh.h animationlist.h e_md2mesh.h
	$(CPP) -c main.cpp -o Win32/Debug/main.o $(CXXFLAGS)

Win32/Debug/Animation_private.res: Win32/Debug/Animation_private.rc 
	$(WINDRES) --input-format=rc -o Win32/Debug/Animation_private.res $(RCINCS) Win32/Debug/ANIMAT~1.RC -O coff
